Added unit test PKCS CBC
Sumu-Ning/AES pull request #13
Opened 2017-03-17 10:29 UTC by jeremycoppey

TEST_CBC_128_PKCS5_ENCRYPT	Instance Method
TEST_CBC_128_PKCS5_DECRYPT	Instance Method

2017-03-21 07:00 UTC, Sumu-Ning commented
It seems many classes are touched.
Do you mind remove unnecessary classes from the commit, and submit the pull request again?

2017-03-21 07:02 UTC, larshp requested changes
see comments

2017-03-21 07:02 UTC, larshp commented on .abapgit.xml
> -﻿<?xml version="1.0" encoding="utf-8"?>
can you reset the XML files to original for those where the data is not changed?

I'm pretty sure this is due to some endianness problems in abapGit

2017-03-21 07:02 UTC, larshp commented on src/zcl_aes_utility.clas.abap
Can you run the pretty printer for the entire class source? This will make it easier to tell what has actually been changed

2019-01-01 07:48 UTC, larshp commented
closing, no reply

2019-01-01 07:48 UTC, closed without merging